### PR TITLE
Adding a new promotion rule - products exclusion rule

### PR DESCRIPTION
**Pull request by kanwal0801**

### CODE REVIEW

**Comment by BuckBuchanan** [comment]
Thsnks! I'm not having any of the problems on my box that you were having on yours. I suspect that your problems are mostly a result of your session inheriting the shopping cart of a previous session. If you can figure out which order is actually active during checkout then you can be sure it's not somehow inheriting a previous coupon code you entered on a previous checkout attempt, and giving you weird error messages. The easiest way to do this is to add a little extra HTML to one of the templates that prints out the @order.number.

In any case, I've found one big bug that prevents the new rule from working. The #eligible? method has two if statements, but there is no default return value, so it is defaulting to false. This means that every order gets rejected. The simplest fix is to add a "return true" as a third line of the method. You might also consider getting rid of the "return false if" part of the second line, and change that second line to !(order.products.any? [etc])

A second bug that I'm not sure is a bug is this: when I tried to create a coupon using both the "Product Exclusion(s)" and the "Product(s)" rules I got a weird error when I tried to fill in the list of products in the "Product(s)" rule. I wonder if the product_picker javascript is able to handle two product pickers together on the same page?

Finally, please write a unit test for the new model.

**Comment by kanwal0801** [comment]
@BuckBuchanan I pushed the fix and the specs as well. Please verify.

**Comment by BuckBuchanan** [comment]
Everything looks good. I've also confirmed that the problem I was having in admin with the Product(s) rule is not a problem with the new code. I will move ahead with merging and launching this code today.

Thanks!

**Comment by BuckBuchanan** [comment]
Launched to production.

**Pull request merged**
